services:
  django-boards:
    build: .
    container_name: django-boards
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  nginx:
    build: ./infra/nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - django-boards

volumes:
  postgres_data:
  static_volume:
